name       : haskell-resolv
version    : 0.1.1.1
release    : 1
source     :
    - http://hackage.haskell.org/package/resolv-0.1.1.1/resolv-0.1.1.1.tar.gz : 49b12ed2b175cca3f885c06ca6906cde1245c02b6f98f2a95fc20d6a8ae40772
license    : GPL-3.0-only
component  : programming.haskell
summary    : Domain Name Service (DNS) lookup via the libresolv standard library routines
description: |
    Domain Name Service (DNS) lookup via the libresolv standard library routines
builddeps  :
    - haskell-cabal-install
    - haskell-base16-bytestring
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register

