name       : haskell-resolv
version    : 0.1.1.2
release    : 3
source     :
    - https://hackage.haskell.org/package/resolv-0.1.1.2/resolv-0.1.1.2.tar.gz : e43a010843d6abe277835bd5de4faa03b5c29e5f25d5602577ccddba876f9f71
license    : GPL-3.0-only
component  : programming.haskell
summary    : Domain Name Service (DNS) lookup via the libresolv standard library routines
description: |
    Domain Name Service (DNS) lookup via the libresolv standard library routines
builddeps  :
    - haskell-cabal-install
    - haskell-base16-bytestring-devel
rundeps    :
    - devel:
        - haskell-base16-bytestring-devel
networking : yes
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register

