name       : haskell-resolv
version    : 0.1.2.0
release    : 4
source     :
    # Revision 6
    - https://hackage.haskell.org/package/resolv-0.1.2.0/resolv-0.1.2.0.tar.gz : 81a2bafad484db123cf8d17a02d98bb388a127fd0f822fa022589468a0e64671
license    : GPL-3.0-only
component  : programming.haskell
summary    : Domain Name Service (DNS) lookup via the libresolv standard library routines
description: |
    Domain Name Service (DNS) lookup via the libresolv standard library routines
builddeps  :
    - ghc-devel
    - haskell-base16-bytestring-devel
rundeps    :
    - devel :
      - haskell-base16-bytestring-devel
setup      : |
    cp $pkgfiles/6.cabal resolv.cabal
    %haskell_configure
build      : |
    %haskell_build
install    : |
    %haskell_install
    %haskell_register
